// 支持的输入框类型
export const inputTypes = [
    'string',
    'password',
    'number',
    'radio',
    'checkbox',
    'switch',
    'textarea',
    'array',
    'datetime',
    'year',
    'date',
    'time',
    'select',
    'selects',
    'remoteSelect',
    'editor',
    'city',
    'image',
    'images',
    'file',
    'files',
    'icon',
]
export type modelValueTypes = string | number | boolean | object
