export const envBaseCheckUrl = '/index.php/installapi/index/envbasecheck'
export const envNpmCheckUrl = '/index.php/installapi/index/envnpmcheck'
export const testDatabaseUrl = '/index.php/installapi/index/testdatabase'
export const popenWindowUrl = '/index.php/installapi/commandexec/popenwindow'
export const baseConfigUrl = '/index.php/installapi/index/baseconfig'
